# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Batch Stationary Point Solver
#'
#' @param h_array Hessian array with dimensions draws x p x p.
#' @param b_matrix Linear coefficient matrix with dimensions draws x p.
#' @param kappa_thresh Condition-number threshold for near-singularity.
#'
#' @return Numeric matrix of stationary points (draws x p), with NA rows for
#' near-singular or unsolved systems.
#' @keywords internal
stationary_points_batch <- function(h_array, b_matrix, kappa_thresh) {
    .Call(`_brsm_stationary_points_batch`, h_array, b_matrix, kappa_thresh)
}

#' Detailed Batch Stationary Point Solver
#'
#' @param h_array Hessian array with dimensions draws x p x p.
#' @param b_matrix Linear coefficient matrix with dimensions draws x p.
#' @param kappa_thresh Condition-number threshold for near-singularity.
#'
#' @return A list with stationary points, per-draw status codes, and kappa proxies.
#' @keywords internal
stationary_points_batch_details <- function(h_array, b_matrix, kappa_thresh) {
    .Call(`_brsm_stationary_points_batch_details`, h_array, b_matrix, kappa_thresh)
}

#' Convert Prediction Matrix to Long-Format Data Frame
#'
#' @param pred_matrix A matrix of predictions (n_draws x n_points)
#' @param draw_ids Integer vector of draw identifiers
#' @param point_ids Integer vector of point identifiers
#'
#' @return A data frame with columns: draw, point_id, estimate
#' @keywords internal
matrix_to_long_format <- function(pred_matrix, draw_ids, point_ids) {
    .Call(`_brsm_matrix_to_long_format`, pred_matrix, draw_ids, point_ids)
}

