# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert Prediction Matrix to Long-Format Data Frame
#'
#' @param pred_matrix A matrix of predictions (n_draws x n_points)
#' @param draw_ids Integer vector of draw identifiers
#' @param point_ids Integer vector of point identifiers
#'
#' @return A data frame with columns: draw, point_id, estimate
#' @keywords internal
matrix_to_long_format <- function(pred_matrix, draw_ids, point_ids) {
    .Call(`_brsm_matrix_to_long_format`, pred_matrix, draw_ids, point_ids)
}

